name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        spark: [ '2.3', '2.4' ]
        ranger: [ '1.0', '1.1', '1.2', '2.0' ]
    name: Build with Spark ${{ matrix.spark }} / Ranger ${{ matrix.ranger }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          version: 1.8
      - name: Build with Maven
        run: mvn clean install -Pspark-${{ matrix.spark }} -Pranger-${{ matrix.ranger }} -Dmaven.javadoc.skip=true -B -V
